workspace_root: &workspace_root
  ~/repo

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9-stretch

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build-react:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Build react app
          command: npm run build:react

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build-electron-prepare:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Prepare for electron build
          command: npm run build:electron:prepare

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build-linux:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Update apt package list
          command: sudo apt-get update

      - run:
          name: Install build deps
          command: sudo apt-get install fakeroot rpm

      - run:
          name: Build electron app
          command: npm run build:electron:make -- -- -p linux


  build-darwin:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Build electron app
          command: npm run build:electron:make -- -- -p darwin

  build-mas:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Build electron app
          command: npm run build:electron:make -- -- -p mas

  build-win32:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
        name: Use 32-bit arch
        command: sudo dpkg --add-architecture i386

      - run:
          name: Update apt package list
          command: sudo apt-get update

      - run:
          name: Install wine
          command: sudo apt-get install wine32

      - run:
          name: Build electron app
          command: npm run build:electron:make -- -- -p win32

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-n-package:
    jobs:
      - install
      - test:
          requires:
            - install
      - build-react:
          requires:
            - install
      - build-electron-prepare:
          requires:
            - build-react
      - build-linux:
          requires:
            - build-electron-prepare
      - build-darwin:
          requires:
            - build-electron-prepare
      - build-mas:
          requires:
            - build-electron-prepare
      - build-win32:
          requires:
            - build-electron-prepare
